version: 11.6.0.{build}
image: 
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu
configuration: Release
install:
  - git submodule update --init
before_build:
  - dotnet restore
build:
  project: EDDiscovery.sln
for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  after_build:
    - cmd: copy EDDiscovery\bin\Release\net461\EDDiscovery.Portable.zip EDDiscovery.Portable.vs2019.net461.zip
    - cmd: copy EDDiscovery\bin\Release\netcoreapp3.1\EDDiscovery.Portable.zip EDDiscovery.Portable.vs2019.netcore31.zip
  artifacts:
    - path: EDDiscovery.Portable.vs2019.net461.zip
    - path: EDDiscovery.Portable.vs2019.netcore31.zip
-
  matrix:
    only:
      - image: Visual Studio 2017

  after_build:
    - cmd: copy EDDiscovery\bin\Release\net461\EDDiscovery.Portable.zip EDDiscovery.Portable.zip
  artifacts:
    - path: EDDiscovery.Portable.zip
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
    - msbuild /p:Configuration=Release EDDiscovery.sln /p:DefineConstants=NO_SYSTEM_SPEECH
cache:
  - packages -> **\packages.config
